jwt:
  get:
    token:
      uri: /authenticate
  secret: javainuse
spring:
  datasource:
    username: ${username}
    url: jdbc:mysql://localhost:3306/training?useSSL=false
    password: ${password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: '8185'
