jwt:
  get:
    token:
      uri: /authenticate
  secret: javainuse
cache:
  host: localhost
  port: 6379
  default-ttl: 6000
  caches-ttl:
    photo: 3600
spring:
  cache:
    type: redis
    redis:
      cache-null-values: 'true'
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/training?useSSL=false
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: '8080'
